name: car_service
description: Car Service


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logging: ^1.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
  country_code_picker: ^2.0.2

  device_info_plus: ^3.1.0
  package_info_plus: ^1.3.0
  connectivity_plus: ^2.0.2

  provider: ^6.0.1
  country_icons: ^2.0.2
  flutter_vector_icons: ^1.0.0
  font_awesome_flutter: ^9.2.0
  flutter_slidable: ^0.6.0
  dio: ^4.0.1

  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  
  path_provider: ^2.0.7
  flutter_rating_bar: ^4.0.1
 

  progress:
    path:
      ../My-Libraries/packages/progress

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/local/
   - assets/fonts/

  fonts:
    - family: Pyidaungsu
      fonts:
        - asset: assets/fonts/Pyidaungsu-1.8.3_Regular.ttf

 